apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-public-feed
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9021
  liveness:
    path: /public-feed/internal/isAlive
    initialDelay: 10
  readiness:
    path: /public-feed/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: true
  webproxy: true
  prometheus:
    enabled: true
    path: /public-feed/internal/prometheus
  ingresses:
    - https://pam-public-feed.nais.oera.no
    - https://arbeidsplassen.nav.no/public-feed
