apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-public-feed
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9021
  liveness:
    path: /public-feed/internal/isAlive
    initialDelay: 10
  readiness:
    path: /public-feed/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /public-feed/internal/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-public-feed-env-secret
      mountPath: /var/run/secrets/nais.io/vault
  accessPolicy:
    outbound:
      rules:
        - application: pam-search-api
