name: deploy-prod
on:
  release:
    types: [published]

jobs:
  call-workflow:
    uses: navikt/pam-deploy/.github/workflows/deploy-prod.yml@v7
    permissions:
      contents: write
      id-token: write
